services:
  dart-verifier-server:
    build: .
    container_name: dart-verifier-server
    ports:
      - "8081:8081"
    env_file:
      - .env

  #   depends_on:
  #     - redis

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   command: ["redis-server", "--appendonly", "yes", "--save", "60", "1"]
