name: vdsp_verifier_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  ssi: ^2.12.4
  uuid: ^4.5.1
  dotenv: ^4.2.0
  mime: ^2.0.0
  bip39_mnemonic: ^4.0.1
  http: ^1.5.0
  redis: ^4.0.0
  json_annotation: ^4.9.0
  web_socket_channel: ^3.0.3
  dcql: ^1.2.0
  didcomm: ^2.0.3
  meeting_place_core: ^0.0.1-dev.2
  meeting_place_mediator: ^0.0.1-dev.2
  meeting_place_control_plane: ^0.0.1-dev.2
  affinidi_tdk_vdsp: ^1.0.0-dev.2
  affinidi_tdk_didcomm_mediator_client: ^1.0.0-dev.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.5.4
  json_serializable: ^6.8.0

dependency_overrides:
  meta: 1.17.0
